FROM golang:1.23-alpine

  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git

# Set working directory
WORKDIR /go/src/github.com/pennsieve/account-service

# Run tests with no parallelism to avoid DynamoDB GSI consistency issues  
CMD CGO_ENABLED=0 go test -v -p 1 -parallel 1 ./internal/...
